In [8]:
import cv2

In [14]:
image = cv2.imread("images/image.jpeg")
logo = cv2.imread("images/logo.png")

cv2.imshow("image", image)
cv2.imshow("logo", logo)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [12]:
logo_gray = cv2.cvtColor(logo, cv2.COLOR_BGR2GRAY)
ret, thresh_logo = cv2.threshold(logo_gray, 120, 255, cv2.THRESH_BINARY_INV)
# In threshold image, logo part will be white and other parts will be black.
# Actually the parts of image which have value more than 120, will be counted as 1 and others 0.
# 1 means True and 0 is False.
thresh_logo_inv = cv2.bitwise_not(thresh_logo)  # logo parts are 1 (True)

cv2.imshow("threshold logo", thresh_logo)
cv2.imshow("threshold logo invert", thresh_logo_inv)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
rows, columns, channels = logo.shape
# shape of an ndarray in numpy determines: (first demension size, second demension size, third demenstion size , ...)
# which are the same as rows, columns and channels in an image. channels (which is 3 here) shows impact of green red and blue.
# we cut the part of image to be filled with logo.
image_part = image[0:rows, 0:columns]

cv2.imshow("image part", image_part)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
logo_white_bg = cv2.bitwise_and(logo, logo, mask=thresh_logo)  # Bg of logo will be white

empty_part = cv2.bitwise_and(image_part, image_part, mask=thresh_logo_inv)

cv2.imshow("logo no bg", logo_white_bg)
cv2.imshow("image no logo", empty_part)
cv2.waitKey(0)
cv2.destroyAllWindows()
# We have the part of image with a logo shape impty inside it which is filled with black (1).
# Also the logo has a white background (0)
# If we create a new image which has logo_white_bg AND empty_part, we have the part whit logo on it!

In [13]:
part_result = cv2.add(logo_white_bg, empty_part)
cv2.imshow("part with logo", part_result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# Now it's time to put the cought part back to the image
image[0:rows, 0:columns] = part_result
cv2.imshow("image with logo", image)
cv2.waitKey(0)
cv2.destroyAllWindows()